[package]
name = "reveal-yourself"
version = "0.1.0"
authors = ["minagawah <minagawa@tokyo800.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
